// export const Users = [
//   {
//     id: 1,
//     profilePicture: "assets/posts/1.jpg",
//     username: "Bicky Bikram",
//   },
//   {
//     id: 2,
//     profilePicture: "assets/posts/2.jpg",
//     username: "Markib",
//   },
//   {
//     id: 3,
//     profilePicture: "assets/posts/3.jpg",
//     username: "Nirjal Paudel",
//   },
//   {
//     id: 4,
//     profilePicture: "assets/posts/4.jpg",
//     username: "Aju Tamang",
//   },
//   {
//     id: 5,
//     profilePicture: "assets/posts/5.jpeg",
//     username: "handsome kta moh",
//   },
//   {
//     id: 6,
//     profilePicture: "assets/posts/6.jpeg",
//     username: "Shrinkhala Khatiwada",
//   },
//   {
//     id: 7,
//     profilePicture: "assets/posts/7.jpg",
//     username: "Deelip Basnet",
//   },
//   {
//     id: 8,
//     profilePicture: "assets/posts/8.jpg",
//     username: "Rjab Khadka",
//   },
//   {
//     id: 9,
//     profilePicture: "assets/posts/9.jpg",
//     username: "kshitz Upreti",
//   },
//   {
//     id: 10,
//     profilePicture: "assets/posts/10.jpg",
//     username: "Kushal Bogati",
//   },
//   {
//     id: 11,
//     profilePicture: "assets/posts/11.jpg",
//     username: "Suvash Newpane",
//   },
// ];

// export const Posts = [
//   {
//     id: 1,
//     desc: "Love For All, Hatred For None.",
//     photo: "posts/1.jpg",
//     date: "5 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 9,
//   },
//   {
//     id: 2,
//     photo: "posts/2.jpg",
//     date: "15 mins ago",
//     userId: 2,
//     like: 2,
//     comment: 1,
//   },
//   {
//     id: 3,
//     desc: "Every moment is a fresh beginning.",
//     photo: "posts/3.jpg",
//     date: "1 hour ago",
//     userId: 3,
//     like: 61,
//     comment: 2,
//   },
//   {
//     id: 4,
//     photo: "posts/4.jpg",
//     date: "4 hours ago",
//     userId: 4,
//     like: 7,
//     comment: 3,
//   },
//   {
//     id: 5,
//     photo: "posts/5.jpeg",
//     date: "5 hours ago",
//     userId: 5,
//     like: 23,
//     comment: 5,
//   },
//   {
//     id: 6,
//     photo: "posts/6.jpeg",
//     date: "1 day ago",
//     userId: 6,
//     like: 44,
//     comment: 6,
//   },
//   {
//     id: 7,
//     desc: "Never regret anything that made you smile.",
//     photo: "posts/7.jpg",
//     date: "2 days ago",
//     userId: 7,
//     like: 52,
//     comment: 3,
//   },
//   {
//     id: 8,
//     photo: "posts/8.jpg",
//     date: "3 days ago",
//     userId: 8,
//     like: 15,
//     comment: 1,
//   },
//   {
//     id: 9,
//     desc: "Change the world by being yourself.",
//     photo: "posts/9.jpg",
//     date: "5 days ago",
//     userId: 9,
//     like: 11,
//     comment: 2,
//   },
//   {
//     id: 10,
//     photo: "posts/10.jpg",
//     date: "1 week ago",
//     userId: 10,
//     like: 104,
//     comment: 12,
//   },
// ];
